GoogleContainerTools/base-images-docker

Makefile

@raggi Jenkins can't allocate a TTY for `docker run`, so I removed the `-t` flag, ran a test build on this branch, and verified that it worked.

Jenkins can't allocate a TTY, so remove the -t flag

---

cloudbuild.yaml.in

this will ensure security updates are picked up in the cloud build.

prevent container build from using cached images

---

Dockerfile
tests/debian_test.json

The netbase package provides /etc/networks, /etc/protocols, /etc/rpc, /etc/services.
Before this change, the differences in packages between Dockerhub debian:8 and GCP debian8 were:
+ii  ca-certificates          20141019+deb8u3          all          Common CA certificates
+ii  libssl1.0.0:amd64        1.0.1t-1+deb8u6          amd64        Secure Sockets Layer toolkit - shared libraries
+ii  openssl                  1.0.1t-1+deb8u6          amd64        Secure Sockets Layer toolkit - cryptographic utility
-ii  inetutils-ping           2:1.9.2.39.3a460-3       amd64        ICMP echo tool
-ii  iproute2                 3.16.0-2                 amd64        networking and traffic control tools
-ii  netbase                  5.3                      all          Basic TCP/IP networking system …

Add 'netbase' package to base image.

---

build.sh
reproducible/cloudbuild.yaml

This makes the reproducible/cloudbuild.yaml take the same parameters as the existing cloudbuild.yaml, and switches our build script to call that by default.

Switch over to the reproducible debian images by default.

---

reproducible/BUILD
reproducible/debootstrap.bzl

The image had the correct path set, but I'm not really sure
where it came from. Maybe a default in docker run? There was already
a test.
The image didn't have a CMD set though, and I can't tell where that
was coming from in the old image. It's not in the Dockerfile. Maybe
a default in docker build? We don't currently have a way to test this,
I'll open an issue in structure test to add one.

Add PATH and CMDs.

---

package_managers/apt_get/apt_get.bzl
package_managers/install_pkgs.bzl

short_path does not work for generated files.
Ref:
https://docs.bazel.build/versions/master/skylark/lib/File.html#path

Use File.path instead of File.short_path.

---

package_managers/install_pkgs.bzl

I got this error message when install_pkgs rule is referenced as an external repository.
ERROR: /usr/local/google/home/xingao/gitrepos/bazel-toolchains/rules/BUILD:31:1: SkylarkAction rules/debian8-clang-with-pkgs.tar.unstripped failed (Exit 1)
+ source ../base_images_docker/util/image_util.sh
bazel-out/k8-fastbuild/bin/rules/debian8-clang-with-pkgs.build: line 4: ../base_images_docker/util/image_util.sh: No such file or directory
With this change, when referencing externally, the correct path (external/base_images_docker/util/image_util.sh) is used.

Fix path for _image_utils attribute.

---

dockerfile_build/dockerfile_build.bzl
node/reproducible/BUILD
tests/dockerfile_build/BUILD
ubuntu/BUILD

rule.
This makes it easier to use these in other dependent rules.

Add a dockerfile_build macro that wraps the tar output in a docker_build

---

package_managers/installer.sh.tpl

I hit this in working on #153. Some tools expect a /tmp dir to exist.

Don't delete /tmp itself, just the contents.

---

tests/util/BUILD
util/run.bzl

When multiple container_run_and_extract rules are extracting the same
file, the name of the output file will conflict with each other. So
instead of putting the file in the root directory of output file tree,
putting the output file in <root>/<name_of_the_rule>/

Allow multiple container_run_and_extract extracting file with same name.

---

package_managers/download_pkgs.bzl
tests/package_managers/BUILD

The deb package tarball will be created under ${WORKDIR}/ in the docker
container while the 'docker cp' command which copies the tarball outside
the contaienr expect the tarball to be at /. If WORKDIR of the base
container is set to a path other than /, the 'docker cp' command will
fail.

Always run download script in docker with workdir "/"

---

package_managers/download_pkgs.bzl

To avoid conflict between existing cache and newly fetched index.
Example error:
W: Size of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty-backports_main_binary-amd64_Packages.gz is not what the server reported 14713 14809

Remove apt-get cache before apt-get update.

---

bootstrap_image.sh

Before the change, the bazel cmd constructed is like the following:
bazel build //container/debian8-clang-fully-loaded:bootstrap_rbe_debian8_toolchain --action_env=GIT_ROOT=/my/path '--sandbox_writable_path=/my/path --verbose_failures --sandbox_debug'
This gives error: 
I/O exception during sandboxed execution: /my/path--verbose_failures --sandbox_debug (No such file or directory)

Fix quotation mark when constructing bazel cmds.

---

CONTRIB.md

#182 took a dependency on the `--delete` flag of tar, which is missing on my version of OSX.
Brew installing a newer one works for me.

Add some documentation on getting a workable version of tar.

---

package_managers/bootstrap_image.bzl
package_managers/install_pkgs.bzl

This enable users to execute commands after installing deb packages. It
is very useful, for example, to remove files that vary build to build
specific to a deb package. For python3.4 installation, .pyc files under
/usr/lib/python3.4/__pycache__/ vary from build to build. With this
extra attribute, if users want to install python3.4 and ensure
reproducibility, they can set post_installation_script to be "rm -rf
/usr/lib/python3.4/__pycache__/".
This commit also adds removing /var/log/alternatives.log as part of
every package installation.

Add installation_cleanup_commands attr in install_pkgs.

---

package_managers/install_pkgs.bzl

/run/mount folder does not exist by default, which makes the touch
command fail, and all the following cleanup commands will not run.

Fix touch /run/mount/utab.

---

WORKSPACE
package_managers/apt_key.bzl
package_managers/download_pkgs.bzl
package_managers/install_pkgs.bzl
tests/package_managers/BUILD
util/run.bzl

Similar idea as previous PRs to refactor install_pkgs (#194), and download_pkgs (#196).

Expose add_apt_key rule's impl, attrs and outputs.

---

util/config_stripper.py

Previously, it was only removed from 'container_config'. But it is
observed to appear in the 'config' sometimes as well.

Strip away 'Hostname' from 'config' as well.

---

package_managers/apt_key.bzl

The plus operator on dicts is deprecated in Bazel and will be removed soon.

Remove usages of + on dicts

---

package_managers/apt_key.bzl
package_managers/download_pkgs.bzl
package_managers/install_pkgs.bzl
tests/package_managers/BUILD
tests/util/BUILD
tests/util/image_loader_test.sh
util/BUILD
util/commit.sh.tpl
util/extract.sh.tpl
util/image_loader.sh
util/run.bzl

Also removed now redundant macros from run.bzl

Remove 'bazel/$package:$tag' naming format requirements from add_apt_key, install_pkgs, and download_pkgs rules

---

WORKSPACE
debian/reproducible/BUILD
debian/reproducible/README.md

ncurses:  `5.9 20140913-1+deb8u3` from `5.9 20140913-1+deb8u2`
procps: `2:3.3.9-9 deb8u1` from `2:3.3.9-9`
```
➜  container-diff diff daemon://bazel/debian/reproducible:debian8 remote://gcr.io/google-appengine/debian8:latest
-----Apt-----
PACKAGE              IMAGE1 (bazel/debian/reproducible:debian8)        IMAGE2 (gcr.io/google-appengine/debian8:latest)
-base-files          8 deb8u11, 413K                                   8 deb8u10, 413K
-gnupg               1.4.18-7 deb8u5, 4.8M                             1.4.18-7 deb8u4, 4.8M
-gpgv                1.4.18-7 deb8u5, 414K                             1.4.18-7 deb8u4, 414K
-libncurses5         5.9 20140913-1+deb8u3, 270K                       5.9 20140913-1+deb8u2, 270K
-libncursesw5        5.9 20140913-1+deb8u3, 353K …
```

Update debian snapshot for ncurses and procps CVEs

---

util/run.bzl

Has been migrated to [https://github.com/bazelbuild/rules_docker/blob/87230912ceaa782b50a8b953338ffa17eac4a9db/contrib/rename_image.bzl](https://github.com/bazelbuild/rules_docker/blob/87230912ceaa782b50a8b953338ffa17eac4a9db/contrib/rename_image.bzl)

Remove unused _rename_image macro

---

WORKSPACE
package_managers/apt_key.bzl

Needed to fix breakage in bazel-toolchains because of https://github.com/bazelbuild/rules_docker/commit/9fd09b30ab07f224ff3a7455c44b58154c0e2e5b
The "install" rule in base-images-docker generates actions with conflicting outputs due to this new implicit output in container_image in rules_docker. This PR ensures the container_image properly overrides the digest name to avoid this conflict

Pass in output digest name when calling container_image

---

util/commit.sh.tpl

@tejal29 @sharifelgamal container_run_and_commit doesn't actually wait for the container to finish running before it commits. This means the modifications made by long running commands won't be committed

Wait for container to finish in run_and_commit

---

util/run.bzl

Parameterizing the impl function allows invoking the rule multiple times
from single rule. Without this, the actions will generate conflicting
artifacts
Also removed unnecessary/unused runtimes from template expansion

Parameterize the commit impl for ease of reuse

---

WORKSPACE
package_managers/apt_key.bzl

Register the new docker toolchain rule being used by rules_docker
container rules

Update rules_docker pin and support new bazel toolchain rules

---

WORKSPACE
package_managers/apt_key.bzl

This reverts commit a465fd842e7adf79f9af637af4ad6c3e1076cd0c.
This change broke our integration tests.

Revert "Update rules_docker pin and support new bazel toolchain rules"

---

WORKSPACE
debian/reproducible/BUILD

```
➜ container-diff diff daemon://bazel/debian/reproducible:debian9 remote://gcr.io/google-appengine/debian9:latest --type=apt
-----Apt-----
Packages found only in bazel/debian/reproducible:debian9: None
Packages found only in gcr.io/google-appengine/debian9:latest: None
PACKAGE             IMAGE1 (bazel/debian/reproducible:debian9)        IMAGE2 (gcr.io/google-appengine/debian9:latest)
-base-files         9.9 deb9u6, 333K                                  9.9 deb9u5, 333K
-gpgv               2.1.18-8~deb9u3, 721K                             2.1.18-8~deb9u2, 721K
-libsystemd0        232-25 deb9u6, 653K                               232-25 deb9u4, 653K
-libudev1           232-25 deb9u6, 223K                               232-25 deb9u4, 223K
-tzdata             2018g-0 …
```

Bump debian snapshot

---

WORKSPACE

The new version of bazel deprecated "git_repository" as a native rule.

---

WORKSPACE

Cloud build was broken on previous changes because bazel image does not include a host go sdk.  This fix downloads an sdk and pins it.  This fixes the issue with having cross compiling toolchains installed.  Tested on desktop and cloudbuild.  Highly suspect this will work in Travis and Kokoro

Cloud build was broken on previous changes

---

WORKSPACE
tests/ubuntu/ubuntu_18_test.yaml
ubuntu/BUILD

From local builds:
```
➜ container-diff diff daemon://gcr.io/gcp-runtimes/ubuntu_16_0_4:latest daemon://ubuntu_16:bazel --type=apt
-----Apt-----
Packages found only in ubuntu:bazel: None
PACKAGE                 IMAGE1 (gcr.io/gcp-runtimes/ubuntu_16_0_4:latest)        IMAGE2 (ubuntu:bazel)
-apt                    1.2.29, 3.3M                                             1.2.29ubuntu0.1, 3.3M
-curl                   7.47.0-1ubuntu2.11, 331K                                 7.47.0-1ubuntu2.12, 331K
-libapt-pkg5.0          1.2.29, 2.7M                                             1.2.29ubuntu0.1, 2.7M
-libcurl3-gnutls        7.47.0-1ubuntu2.11, 543K                                 7.47.0-1ubuntu2.12, 543K …
```

Bump ubuntu shapshots

---

WORKSPACE

-----Apt-----
Packages found only in bazel/ubuntu:bootstrap_ubuntu_16_0_4: None
PACKAGE                   IMAGE1 (gcr.io/gcp-runtimes/ubuntu_16_0_4:latest)        IMAGE2 (bazel/ubuntu:bootstrap_ubuntu_16_0_4)
-base-files               9.4ubuntu4.7, 312K                                       9.4ubuntu4.8, 312K
-libc6                    2.23-0ubuntu10, 10.7M                                    2.23-0ubuntu11, 10.7M
-libkmod2                 22-1ubuntu5.1, 118K                                      22-1ubuntu5.2, 118K
-libsystemd0              229-4ubuntu21.15, 620K                                   229-4ubuntu21.16, 620K
-libudev1                 229-4ubuntu21.15, 206K …

Updating ubuntu xenial to 16.04.6

---

WORKSPACE
ubuntu/BUILD

No CVEs in the 16.0.4 image currently, but bumping it anyway
```
➜  container-diff diff daemon://gcr.io/gcp-runtimes/ubuntu_16_0_4:latest daemon://bazel/ubuntu:ubuntu_16_0_4 --type=apt
-----Apt-----
Packages found only in bazel/ubuntu:ubuntu_16_0_4: None
PACKAGE               IMAGE1 (gcr.io/gcp-runtimes/ubuntu_16_0_4:latest)        IMAGE2 (bazel/ubuntu:ubuntu_16_0_4)
-apt                  1.2.29ubuntu0.1, 3.3M                                    1.2.31, 3.4M
-libapt-pkg5.0        1.2.29ubuntu0.1, 2.7M                                    1.2.31, 2.8M
-libsystemd0          229-4ubuntu21.16, 620K                                   229-4ubuntu21.21, 620K
-libudev1             229-4ubuntu21.16, 206K …
```

bump ubuntu snapshots

---

WORKSPACE

Updated WORKSPACE generated by script in #299
Internal issue ref: 131401908
```
----Apt-----
Packages found only in bazel/ubuntu:bootstrap_ubuntu_16_0_4: None
PACKAGE                 IMAGE1 (bazel/ubuntu:bootstrap_ubuntu_16_0_4)        IMAGE2 (gcr.io/gcp-runtimes/ubuntu_16_0_4:latest)                                                                                        
-ca-certificates        20170717~16.04.2, 426K                               20170717~16.04.1, 426K
-gcc-5-base             5.4.0-6ubuntu1~16.04.11, 66K                         5.4.0-6ubuntu1~16.04.10, 66K
-libssl1.0.0            1.0.2g-1ubuntu4.14, 3.3M                             1.0.2g-1ubuntu4.13, 3.3M
-libstdc++6 …
```

Update xenial to 20190425

---

ubuntu/scripts/upload-latest.sh

This is intended to take some toil and room for error out of our playbook entry.

Add script to upload latest Ubuntu image to GCS

---

WORKSPACE
package_managers/apt_key.bzl

https://github.com/bazelbuild/rules_docker/pull/818 added a new
output_config attr that must be properly overriden in apt_key
This PR depends on https://github.com/GoogleContainerTools/base-images-docker/pull/306 (which updates pin to rules_docker to after PR 818 linked above)

use new output_config attr properly

---

debian9/WORKSPACE
debian9/cloudbuild.yaml
debian9/test.yaml
ubuntu1604/WORKSPACE
ubuntu1604/cloudbuild.yaml
ubuntu1804/WORKSPACE
ubuntu1804/cloudbuild.yaml

We installed docker in l.gcr.io/google/bazel, so now switch to that to generate containers.
Standardize to double quotation mark in cloudbuild.yaml files.

Bump dependency pins and some clean up.

---

ubuntu1604/WORKSPACE
ubuntu1604/cloudbuild.yaml
ubuntu1804/cloudbuild.yaml

Updates the reference to base-images-docker to HEAD. Also adds error
logging to the container tests.

Revert reference to local_repository that results in infinite symlink

---

BUILD
package_managers/download_pkgs.bzl
tests/package_managers/BUILD

The CSV file will list every package and their respective versions
included in the output tarball produced by the download_pkgs rule.

Add metadata CSV output for download_pkgs rule

---

WORKSPACE

Package differences:
1 for 18_0_4 image:
```
base-images-docker: (master)$ container-diff diff  daemon://bazel/ubuntu:ubuntu_18_0_4  remote://gcr.io/gcp-runtimes/ubuntu_18_0_4:latest
Starting diff on images daemon://bazel/ubuntu:ubuntu_18_0_4 and remote://gcr.io/gcp-runtimes/ubuntu_18_0_4:latest, using differs: [apt]
Computing diffs
-----Apt-----
Packages found only in bazel/ubuntu:ubuntu_18_0_4: None
Packages found only in gcr.io/gcp-runtimes/ubuntu_18_0_4:latest: None
PACKAGE             IMAGE1 (bazel/ubuntu:ubuntu_18_0_4)        IMAGE2 (gcr.io/gcp-runtimes/ubuntu_18_0_4:latest)
-bzip2              1.0.6-8.1ubuntu0.1, 177K                   1.0.6-8.1, 177K
-libbz2-1.0         1.0.6-8.1ubuntu0.1, 90K                    1.0.6-8.1, 90K
-libsystemd0 …
```

Update ubuntu 16_0_4 and 18_0_4 to pick up security fixes

---

ubuntu1604/cloudbuild.yaml
ubuntu1804/cloudbuild.yaml

Signed-off-by: Tejal Desai <tejaldesai@google.com>
So, the this latest cloud build failed step 2
https://pantheon.corp.google.com/cloud-build/builds/4ff9d991-09e1-4555-81aa-b08e6f40f28a?project=gcp-runtimes&organizationId=433637338589 with 
```
FAILED: Build did NOT complete successfully
Executed 0 out of 1 test: 1 fails to build.
FAILED: Build did NOT complete successfully
INFO: 6 processes: 6 linux-sandbox.
INFO: Elapsed time: 15.715s, Critical Path: 4.90s
Use --verbose_failures to see the command lines of failed build steps.
Target //:image-test failed to build
[41 / 46] 1 / 1 tests, 1 failed; checking cached actions
----------------
If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run …
```

add flags for all the bazel commad in cloud build.

---

ubuntu1604/.bazelrc
ubuntu1604/BUILD
ubuntu1604/WORKSPACE
ubuntu1604/deps_spec.yaml
ubuntu1604/file_updates.yaml

Enabling metadata about debian packages included in the debian package
tarball tracked by file update service and generate a file with a
summary of the changes introduced by a pull request generated by
dependency update service.

Enabling debian package metadata information for ubuntu 16.04

---

ubuntu1604/deps_spec.yaml
ubuntu1604/file_updates.yaml

This should trigger an update regardless of whether the debian packages
had an update or the base image. Previously, an update would be
triggered by a debian package update only.

Run security check for ubuntu base image updates as well

---

centos7/cloudbuild.yaml
debian9/cloudbuild.yaml
ubuntu1604/cloudbuild.yaml
ubuntu1804/cloudbuild.yaml

There are conflicting actions when the --output_base is at the root of the Bazel project itself.

Fix --output_base problem

---

WORKSPACE
centos7/WORKSPACE
debian9/BUILD
debian9/WORKSPACE
tests/package_managers/BUILD
ubuntu1604/BUILD
ubuntu1604/WORKSPACE
ubuntu1804/BUILD
ubuntu1804/WORKSPACE

All rules needed for container building / releasing have been moved to rules_docker. Single dep should be easier to handle. We will be setting up later this week the DUS service to automatically update the rules_docker pin after every release.

remove dependency on bazel-toolchains repo

---

WORKSPACE
debian10/WORKSPACE

Okay, first we have to point debian_base to a valid debian image, and then the FUS service will generate another one from scratch and populate google-appengine gcr.

Point debian_base to valid image

---

centos7/build.sh

To fix https://github.com/GoogleContainerTools/base-images-docker/issues/913 
Restore `/var/lib/rpm/Packages` so that CVE scanners can read OS packages on CentOS7 image.

centos7: restore rpm packages to allow CVE scans

---

centos7/WORKSPACE
centos7/revisions.bzl
debian10/WORKSPACE
debian10/revisions.bzl
debian9/WORKSPACE
debian9/revisions.bzl
ubuntu1604/WORKSPACE
ubuntu1604/revisions.bzl
ubuntu1804/WORKSPACE
ubuntu1804/revisions.bzl

This fixes building FUS targets with the latest Bazel 3.4.1.
`gflags` was removed from `bazel_tools` which is now reflected in the latest release of `rules_docker`.

Update rules_docker version

---

ubuntu2004/revisions.bzl

debs: https://storage.googleapis.com/container-deps/ubuntu2004/debs/1633037528_debs.tar
tar: https://storage.googleapis.com/container-deps/ubuntu2004/tar/1633041097_ubuntu2004.tar.gz

The cache is populated, point to real values

---

centos7/build.sh

Removing the extracted java ca-certs was one of the ways we ensured the image would remain stable on rebuild, but it causes larger problems for users.

Leave extracted java ca-certs in place
