GoogleContainerTools/base-images-docker

.gitignore
build.sh
cloudbuild.yaml

Ref #29 
What do you think? I have envsubst on my desktop by default, I wonder if it'll be available on our CI machines.

Switch to envsubst from sed.

---

cloudbuild.yaml.in

add intermediate build step to check if target exists in remote repository

---

.travis.yml
build.sh
test.sh

Add shellcheck to travis.

---

cloudbuild_securitytest.yaml

adding special cloudbuild for security tests

---

build.sh

minor build script refactoring

---

build.sh

@nkubala 
cc @dlorenc 
-v wasn't shifting properly so I needed to fix that. also changing indentation so vim stops yelling at me.

fixing build

---

tests/debian_test.json
tests/security_test.json

fix debian test json

---

.gitignore
build.sh
mkdebootstrap/Dockerfile.in

adding the ability to build debian stretch

---

tests/debian_test.json
tests/security_test.json

to merge after https://github.com/GoogleCloudPlatform/runtimes-common/pull/49
@dlorenc

update test config to match latest schema

---

build.sh

switch container build command from alpha to beta

---

.gitignore
build.sh

making yaml file configurable in build

---

cloudbuild.yaml.in

https://github.com/GoogleCloudPlatform/runtimes-common/pull/76
@dlorenc @sharifelgamal

remove python call from tag check args

---

dockerfile_build/config_stripper.py

This doesn't appear to be strictly necessary (docker happily loads a config with a name not matching it's digest), but we should probably do this anyway.

Update the config file path in the config_stripper.

---

dockerfile_build/BUILD
dockerfile_build/dockerfile_build.bzl
dockerfile_build/test/BUILD
reproducible/debootstrap.bzl
reproducible/ubuntu/nodebootstrap.bzl

Stop generating .tars for images.

---

dockerfile_build/BUILD
dockerfile_build/Dockerfile.2
dockerfile_build/dockerfile_build.bzl
dockerfile_build/test/BUILD
dockerfile_build/test/test2.yaml
reproducible/mkimage.sh

This should fix what you're trying to do in #119

Fix docker_file build rule for use with chaining.

---

tests/presubmit/presubmit.sh

This will make iteration on tests quicker.

Move the signing check to the end.

---

WORKSPACE
dockerfile_build/BUILD
reproducible/ubuntu/BUILD
reproducible/ubuntu/images_release.yaml
reproducible/ubuntu/node_gen_tar.sh
reproducible/ubuntu/test/BUILD

WIP: ubuntu and node releases using cloudbuild.yaml and build.sh

---

package_managers/apt_get/apt_get.bzl

This might help track down why travis is failing.

Add some debug commands.

---

package_managers/package_manager_provider.bzl
tests/package_managers/apt_get/BUILD

Add fields to provider

---

package_managers/apt_get/apt_get.bzl

Fix deb installl.

---

package_managers/install_pkgs.bzl
util/BUILD
util/image_util.sh

I want to re-use this function in @nkubala's run_and_commit helper.

Refactor image entrypoint resetting.

---

WORKSPACE
tests/util/BUILD
tests/util/container_commit.yaml
util/commit.sh.tpl
util/image_util.sh
util/run.bzl

Use the refactored image_util script in run_and_commit.

---

Makefile
bootstrap_image.sh
package_managers/apt_get/repos.bzl
package_managers/bootstrap_image.bzl
package_managers/download_pkgs.bzl
store/BUILD
store/git/BUILD
store/git/git.bzl
store/git/git.py
tests/package_managers/BUILD
tests/package_managers/test_bootstrap_image_macro.sh
tests/package_managers/test_complex_packages.sh
tests/store/BUILD
tests/store/git/BUILD
tests/store/git/git_test.py

Putting this up to get some early feedback
Why is this not a shell script:
While writing a script it was evident the shell script will require a number of parameters describing list of packages to install in the image.

Macro for bootstrap image

---

WORKSPACE
dockerfile_build/dockerfile_build.bzl
package_managers/install_pkgs.bzl
ubuntu/BUILD
util/config_stripper.py

Making builds truly reproducible

---

WORKSPACE

Fix this by switching to skylark git_repository, and adding some
transitive deps manually.
Ref https://github.com/angular/angular/pull/22406

Bazel/git_repository is broken.

---

.travis.yml
check-fmt.sh

Disable shellcheck.

---

BUILD
Makefile
WORKSPACE
check-fmt.sh
package_managers/install_pkgs.bzl
tests/package_managers/test_complex_packages.sh
ubuntu/BUILD
util/config_stripper.py

Update Ubuntu 18

---

WORKSPACE
debian/reproducible/BUILD

Update debian snapshot.

---

README.md

Add links to READMe

---

WORKSPACE
tests/package_managers/BUILD

Added reproducibility test for install_pkgs rule
Also updated dependencies, as new rules needed to be used for this.

Add reproducibility test

---

ubuntu/BUILD

procps: `2:3.3.10-4ubuntu2.4` from `2:3.3.10-4ubuntu2.3`
```
➜  container-diff diff daemon://bazel/ubuntu:ubuntu_16_0_4 remote://gcr.io/gcp-runtimes/ubuntu_16_0_4:latest 
-----Apt-----
Packages found only in bazel/ubuntu:ubuntu_16_0_4: None
PACKAGE                 IMAGE1 (bazel/ubuntu:ubuntu_16_0_4)        IMAGE2 (gcr.io/gcp-runtimes/ubuntu_16_0_4:latest)
-curl                   7.47.0-1ubuntu2.8, 331K                    7.47.0-1ubuntu2.7, 331K
-gnupg                  1.4.20-1ubuntu3.2, 1.6M                    1.4.20-1ubuntu3.1, 1.6M
-gpgv                   1.4.20-1ubuntu3.2, 430K                    1.4.20-1ubuntu3.1, 430K
-libcurl3-gnutls        7.47.0-1ubuntu2.8, 543K …
```

Update ubuntu tars for procps CVE

---

WORKSPACE
tests/package_managers/BUILD

Also changed a parameter name that was renamed in rules_docker

Updated rules_docker version

---

util/run.bzl

@sharifelgamal @tejal29 Please have a look at this PR. The change exports the attributes, implementation and outputs of container_run_and_commit so that it can be used by other rules

Export run_and_commit attributes for use by other rules

---

package_managers/apt_key.bzl
tests/util/BUILD
util/extract.sh.tpl
util/run.bzl

* modified existing test to add new attribute docker_run_flags
* exposed the build script as an output so that tests can validate
its contents
* added test that verifies build script contains docker_run_flags

enable passing additional flags to docker run command in run_and_extract

---

WORKSPACE
ubuntu/BUILD

Trying Nick's update over with a gpg signed commit

Update ubuntu snapshots - dmccasland edition

---

debian/reproducible/debootstrap.bzl
dockerfile_build/dockerfile_build.bzl
package_managers/apt_key.bzl
package_managers/download_pkgs.bzl
package_managers/install_pkgs.bzl
util/run.bzl

- single_file is deprecated.
- new_file is deprecated.
- template_action is deprecated.

Fix Bazel compatible issues.

---

WORKSPACE
debian/reproducible/BUILD

Signed-off-by: Dan Lorenc <lorenc.d@gmail.com>

Update Debian to 9.7

---

BUILD
download_pkgs_at_root_run_test.sh
package_managers/download_pkgs.bzl
tests/package_managers/BUILD

Fix download_pkg rule when declared at project root.

---

WORKSPACE
debian/reproducible/BUILD

Updating debian snapshot to pick up new systemd to address security CVEs

Updating debian snapshot

---

util/config_stripper.py

Related: https://github.com/bazelbuild/bazel/issues/1299

Fix file mtime in the container to not confuse other programs.

---

ubuntu1604/WORKSPACE
ubuntu1804/WORKSPACE

https://github.com/GoogleContainerTools/base-images-docker/pull/311

Update base-images-docker to include mtime fix.

---

package_managers/BUILD
package_managers/security_check.py

List of changes:
1. Internal imports changed to equivalent external versions.
2. Function gcloud_path changed to return "gcloud" instead of internal
path to gcloud binary.
3. Added call to logging.basicConfig in function _main to ensure
messages at level info or above get printed.

Add image CVE checker script

---

ubuntu1604/cloudbuild.yaml
ubuntu1804/cloudbuild.yaml

Signed-off-by: Tejal Desai <tejaldesai@google.com>

add flags so that our old rules can work with latest bazel

---

ubuntu/images_release.yaml
ubuntu1604/cloudbuild.yaml
ubuntu1804/cloudbuild.yaml

Signed-off-by: Tejal Desai <tejaldesai@google.com>
Verified the cloud build locally on my desktop
The successful builds are:
https://pantheon.corp.google.com/cloud-build/builds/3afb4a23-3fca-40b8-a13b-f624c6870083?project=gcp-runtimes
and 
https://pantheon.corp.google.com/cloud-build/builds/a21378a4-1056-4263-89fb-4c39e8a0d1ee?project=gcp-runtimes

fix cloudbuild.yaml on master 

---

centos7/cloudbuild.yaml
debian9/cloudbuild.yaml
ubuntu1604/cloudbuild.yaml
ubuntu1804/cloudbuild.yaml

Updating cloudbuild to push to multiple registries and note that prod…uction riggers specify the real push targets

Updating cloudbuild for multiple registries

---

centos7/BUILD
centos7/cloudbuild.yaml
debian9/BUILD
debian9/cloudbuild.yaml
ubuntu1604/BUILD
ubuntu1604/cloudbuild.yaml
ubuntu1804/BUILD
ubuntu1804/cloudbuild.yaml

Also switched the images the security check runs on to prod.

Switch image destination to prod

---

centos7/WORKSPACE
debian10/WORKSPACE
debian9/WORKSPACE
ubuntu1604/WORKSPACE
ubuntu1804/WORKSPACE

Pinning rules docker to version 0.14.4

Pin rules docker

---

ubuntu2004/BUILD
ubuntu2004/WORKSPACE

I think this might fix the kokoro builds (we need to seed somehow)
fyi @Abiswas2017

temporary pull image from dockerhub while we build out the cache
